var w=2;
var n=1;
var nn=1.5;
var nnn=1.75;
var wn=2;
var wnn=2;

var films = {
    "12 Years a Slave":2013,
    "Gravity":2013,
    "Wolf of Wall Street":2013,
    "American Hustle":2013,
    "Philomena":2013,
    "Nebraska":2013,
    "Captain Phillips":2013,
    "Dallas Buyers Club":2013,
    "Her":2013,
    "Argo":2012,
    "Amour":2012,
    "Beasts of the Southern Wild":2012,
    "Django Unchained":2012,
    "Les Miserables":2012,
    "Life of Pi":2012,
    "Lincoln":2012,
    "Silver Linings Playbook":2012,
    "Zero Dark Thirty":2012,
    "The Descendants":2011,
    "The Artist":2011,
    "Extremely Loud and Incredibly Close":2011,
    "The Help":2011,
    "Hugo":2011,
    "Midnight in Paris":2011,
    "Moneyball":2011,
    "The Tree of Life":2011,
    "War Horse":2011,
    "The King's Speech":2010,
    "127 Hours":2010,
    "Black Swan":2010,
    "The Fighter":2010,
    "Inception":2010,
    "The Kids Are All Right":2010,
    "The Social Network":2010,
    "Toy Story 3":2010,
    "True Grit":2010,
    "Winter's Bone":2010,
    "The Hurt Locker":2009,
    "Avatar":2009,
    "The Blind Side":2009,
    "District 9":2009,
    "An Education":2009,
    "Inglourious Basterds":2009,
    "Precious":2009,
    "A Serious Man":2009,
    "Up":2009,
    "Up in the Air":2009,
    "Slumdog Millionaire":2008,
    "The Curious Case of Benjamin Button":2008,
    "Frost/Nixon":2008,
    "Milk":2008,
    "The Reader":2008,
    "No Country for Old Men":2007,
    "Atonement":2007,
    "Juno":2007,
    "Michael Clayton":2007,
    "There Will Be Blood":2007,
	"Million Dollar Baby":2004,	"The Lord of the Rings: The Return of the King":2003,	"Chicago":2002,	"A Beautiful Mind":2001,	"Gladiator":2000,	"American Beauty":1999,"Shakespeare in Love":1998,"Titanic":1997,"The English Patient":1996,"Braveheart":1995,"Forrest Gump":1994,"Schindler's List":1993,"Unforgiven":1992,"Silence of the Lambs":1991,"Dances with Wolves":1990,"Driving Miss Daisy":1989,"Rain Man":1988,"The Last Emperor":1987,"Platoon":1986,"Out of Africa":1985,"Amadeus":1984,"Terms of Endearment":1983,"Gandhi":1982,"Chariots of Fire":1981,"Ordinary People":1980,"Finding Neverland":2004,"Ray":2004,"Sideways":2004,"The Aviator":2004,"Master and Commander: The Far Side of the World":2003,"Lost in Translation":2003,"Mystic River":2003,"Seabiscuit":2003,"Gangs of New York":2002,"The Hours":2002,"The Lord of the Rings: The Two Towers":2002,"The Pianist":2002,"Moulin Rouge":2001,"The Lord of the Rings: The Fellowship of the Ring":2001,"Gosford Park":2001,"In the Bedroom":2001,"Crouching Tiger, Hidden Dragon":2000,"Chocolat":2000,"Erin Brockovich":2000,"Traffic":2000,"The Cider House Rules":1999,"The Green Mile":1999,"The Insider":1999,"The Sixth Sense":1999,"Elizabeth":1998,"Saving Private Ryan":1998,"Life is Beautiful":1998,"The Thin Red Line":1998,"As Good as it Gets":1997,"Good Will Hunting":1997,"L.A. Confidential":1997,"The Full Monty":1997,"Fargo":1996,"Jerry Maguire":1996,"Secrets and Lies":1996,"Shine":1996,"Apollo 13":1995,"Babe":1995,"Sense and Sensibility":1995,"The Postman (Il Postino)":1995,"Four Weddings and a Funeral":1994,"Pulp Fiction":1994,"Quiz Show":1994,"Shawshank Redemption":1994,"In the Name of the Father":1993,"The Fugitive":1993,"The Piano":1993,"The Remains of the Day":1993,"A Few Good Men":1992,"Howard's End":1992,"Scent of a Woman":1992,"The Crying Game":1992,"Beauty and the Beast":1991,"Bugsy":1991,"JFK":1991,"The Prince of Tides":1991,"Awakenings":1990,"Ghost":1990,"Goodfellas":1990,"The Godfather Part III":1990,"Born on the Fourth of July":1989,"Dead Poets Society":1989,"Field of Dreams":1989,"My Left Foot":1989,"Dangerous Liaisons":1988,"Mississippi Burning":1988,"The Accidental Tourist":1988,"Working Girl":1988,"Broadcast News":1987,"Fatal Attraction":1987,"Hope and Glory":1987,"Moonstruck":1987,"A Room with a View":1986,"Children of a Lesser God":1986,"Hannah and her Sisters":1986,"The Mission":1986,"The Color Purple":1985,"Kiss of the Spider Woman":1985,"Prizzi's Honor":1985,"Witness":1985,"A Passage to India":1984,"A Soldier's Story":1984,"Places in the Heart":1984,"The Killing Fields":1984,"Tender Mercies":1983,"The Big Chill":1983,"The Dresser":1983,"The Right Stuff":1983,"E.T.":1982,"Missing":1982,"The Verdict":1982,"Tootsie":1982,"Atlantic City":1981,"On Golden Pond":1981,"Raiders of the Lost Ark":1981,"Reds":1981,"Coal Miner's Daughter":1980,"Raging Bull":1980,"Tess":1980,"The Elephant Man":1980,
"Crash":2005,
"Brokeback Mountain":2005,
"Capote":2005,
"Good Night, and Good Luck":2005,
"Munich":2005,
"The Departed":2006,
"Babel":2006,
"Letters from Iwo Jima":2006,
"Little Miss Sunshine":2006,
"The Queen":2006,
    "The Master":2012,
    "The Sessions":2012,
    "The Impossible":2012,
    "Flight":2012,
    "Moonrise Kingdom":2012,
    "Anna Karenina":2012,
    "Skyfall":2012,
    "Chasing Ice":2012,
    "Ted":2012,
    "The Hobbit: An Unexpected Journey":2012,
    "Hitchcock":2012,
    "Mirror Mirror":2012,
    "Snow White and the Huntsman": 2012,
    "The Avengers":2012,
    "Prometheus":2012,
    "Blue Jasmine":2013,
    "August: Osage County":2013,
    "Before Midnight":2013,
    "The Book Thief":2013,
    "Saving Mr. Banks":2013,
    "Despicable Me 2":2013,
    "Frozen":2013,
    "Mandela: Long Walk to Freedom":2013,
    "All is Lost":2013,
    "The Hobbit: The Desolation of Smaug":2013,
    "Lone Survivor":2013,
    "Inside Llewyn Davis":2013,
    "The Great Gatsby":2013,
    "The Grandmaster":2013,
    "Prisoners":2013,
    "Bad Grandpa":2013,
    "The Lone Ranger":2013,
    "The Invisible Woman":2013,
    "Iron Man 3":2013,
    "Star Trek: Into Darkness":2013,
    "A Better Life":2011,
    "Tinker Tailor Soldier Spy":2011,
    "The Iron Lady":2011,
    "Albert Nobbs":2011,
    "The Girl with the Dragon Tattoo":2011,
    "My Week with Marilyn":2011,
    "Beginners":2011,
    "Warrior":2011,
    "Bridesmaids":2011,
    "Margin Call":2011,
    "A Separation":2011,
    "The Ides of March":2011,
    "The Adventures of Tintin":2011,
    "The Muppets":2011,
    "Rio":2011,
    "Drive":2011,
    "Transformers: Dark of the Moon":2011,
    "Harry Potter and the Deathly Hallows: Part 2":2011,
    "Anonymous":2011,
    "Jane Eyre":2011,
    "Real Steel":2011,
    "Rise of the Planet of the Apes":2011,
    "W.E.":2011,
    "Biutiful":2010,
    "Rabbit Hole":2010,
    "Blue Valentine":2010,
    "The Town":2010,
    "Animal Kingdom":2010,
    "Another Year":2010,
    "How to Train your Dragon":2010,
    "Country Strong":2010,
    "Tangled":2010,
    "Tron: Legacy":2010,
    "Unstoppable":2010,
    "Salt":2010,
    "Alice in Wonderland":2010,
    "Harry Potter and the Deathly Hallows: Part 1":2010,
    "The Wolfman":2010,
    "Barney's Version":2010,
    "The Way Back":2010,
    "I am Love":2010,
    "The Tempest":2010,
    "Hereafter":2010,
    "Iron Man 2":2010,
    "Crazy Heart":2009,
    "A Single Man":2009,
    "Invictus":2009,
    "The Last Station":2009,
    "Julie & Julia":2009,
    "The Messenger":2009,
    "The Lovely Bones":2009,
    "Nine":2009,
    "In the Loop":2009,
    "Fantastic Mr. Fox":2009,
    "Sherlock Holmes":2009,
    "The Princess and the Frog":2009,
    "Paris 36":2009,
    "Star Trek":2009,
    "Transformers: Revenge of the Fallen":2009,
    "The Imaginarium of Dr. Parnassus":2009,
    "The Young Victoria":2009,
    "Harry Potter and the Half-Blood Prince":2009,
    "The White Ribbon":2009,
    "Il Divo":2009,
    "Bright Star":2009,
    "Coco Before Chanel":2009,
    "The Visitor":2008,
    "The Wrestler":2008,
    "Rachel Getting Married":2008,
    "Changeling":2008,
    "Frozen River":2008,
    "Doubt":2008,
    "The Dark Knight":2008,
    "Tropic Thunder":2008,
    "Revolutionary Road":2008,
    "Vicky Cristina Barcelona":2008,
    "Happy-Go-Lucky":2008,
    "In Bruges":2008,
    "WALL-E":2008,
    "Defiance":2008,
    "Iron Man":2008,
    "Wanted":2008,
    "The Duchess":2008,
    "Hellboy II: The Golden Army":2008,
    "Australia":2008,
    "The Diving Bell and the Butterfly":2007,
    "Sweeney Todd: The Demon Barber of Fleet Street":2007,
    "In the Valley of Elah":2007,
    "Eastern Promises":2007,
    "La Vie en Rose":2007,
    "Elizabeth: The Golden Age":2007,
    "Away from Her":2007,
    "The Savages":2007,
    "The Assassination of Jesse James by the Coward Robert Ford":2007,
    "Charlie Wilson's War":2007,
    "Into the Wild":2007,
    "I'm Not There":2007,
    "American Gangster":2007,
    "Gone Baby Gone":2007,
    "Lars and the Real Girl":2007,
    "Ratatouille":2007,
    "The Kite Runner":2007,
    "3:10 to Yuma":2007,
    "Once":2007,
    "Enchanted":2007,
    "August Rush":2007,
    "The Bourne Ultimatum":2007,
    "Transformers":2007,
    "The Golden Compass":2007,
    "Norbit":2007,
    "Pirates of the Caribbean: At World's End":2007,
    "Across the Universe":2007,
    "United 93":2006,
    "The Last King of Scotland":2006,
    "Blood Diamond":2006,
    "Half Nelson":2006,
    "Venus":2006,
    "The Pursuit of Happyness":2006,
    "Volver":2006,
    "Notes on a Scandal":2006,
    "The Devil Wears Prada":2006,
    "Little Children":2006,
    "Dreamgirls":2006,
    "Pan's Labyrinth":2006,
    "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan":2006,
    "Children of Men":2006,
    "The Good German":2006,
    "An Inconvenient Truth":2006,
    "Cars":2006,
    "Apocalypto":2006,
    "Flags of our Fathers":2006,
    "Pirates of the Caribbean: Dead Man's Chest":2006,
    "The Good Shepherd":2006,
    "The Prestige":2006,
    "The Black Dahlia":2006,
    "The Illusionist":2006,
    "Click":2006,
    "Marie Antoinette":2006,
    "Curse of the Golden Flower":2006,
    "Poseidon":2006,
    "Superman Returns":2006,
    "Hustle & Flow":2005,
    "Walk the Line":2005,
    "Mrs. Henderson Presents":2005,
    "Transamerica":2005,
    "Pride &  Prejudice":2005,
    "North Country":2005,
    "Syriana":2005,
    "Cinderella Man":2005,
    "A History of Violence":2005,
    "The Constant Gardener":2005,
    "Junebug":2005,
    "Match Point":2005,
    "The Squid and the Whale":2005,
    "Memoirs of a Geisha":2005,
    "King Kong":2005,
    "War of the Worlds":2005,
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe":2005,
    "Harry Potter and the Goblet of Fire":2005,
    "Batman Begins":2005,
    "The New World":2005,
    "Star Wars Episode III: Revenge of the Sith":2005,
    "Charlie and the Chocolate Factory":2005,
    "Vera Drake":2004,
    "Hotel Rwanda":2004,
    "Being Julia":2004,
    "Maria Full of Grace":2004,
    "Eternal Sunshine of the Spotless Mind":2004,
    "Collateral":2004,
    "Closer":2004,
    "Kinsey":2004,
    "The Incredibles":2004,
    "The Motorcycle Diaries":2004,
    "Before Sunset":2004,
    "The Village":2004,
    "The Passion of the Christ":2004,
    "Harry Potter and the Prisoner of Azkaban":2004,
    "Lemony Snicket's A Series of Unfortunate Events":2004,
    "The Phantom of the Opera":2004,
    "The Polar Express":2004,
    "The Chorus":2004,
    "Shrek 2":2004,
    "Spider-Man 2":2004,
    "A Very Long Engagement":2004,
    "House of Flying Daggers":2004,
    "The Sea Inside":2004,
    "Troy":2004,
    "I, Robot":2004,
    "City of God":2003,
    "Pirates of the Caribbean: The Curse of the Black Pearl":2003,
    "House of Sand and Fog":2003,
    "Cold Mountain":2003,
    "Monster":2003,
    "Whale Rider":2003,
    "Something's Gotta Give":2003,
    "In America":2003,
    "21 Grams":2003,
    "The Cooler":2003,
    "The Last Samurai":2003,
    "Pieces of April":2003,
    "Thirteen":2003,
    "Dirty Pretty Things":2003,
    "Finding Nemo":2003,
    "The Barbarian Invasions":2003,
    "American Splendor":2003,
    "Big Fish":2003,
    "A Mighty Wind":2003,
    "The Triplets of Belleville":2003,
    "Girl with a Pearl Earring":2003,
    "Talk to Her":2002,
    "Adaptation":2002,
    "The Quiet American":2002,
    "About Schmidt":2002,
    "Frida":2002,
    "Unfaithful":2002,
    "Far from Heaven":2002,
    "Road to Perdition":2002,
    "Catch me if you Can":2002,
    "My Big Fat Greek Wedding":2002,
    "Y tu Mama Tambien":2002,
    "About a Boy":2002,
    "8 Mile":2002,
    "The Wild Thornberrys Movie":2002,
    "Minority Report":2002,
    "Spider-Man":2002,
    "The Time Machine":2002,
    "Star Wars Episode II: Attack of the Clones":2002,
    "Mulholland Dr.":2001,
    "Black Hawk Down":2001,
    "Training Day":2001,
    "I am Sam":2001,
    "Ali":2001,
    "Monster's Ball":2001,
    "Iris":2001,
    "Bridget Jones's Diary":2001,
    "Sexy Beast":2001,
    "Amelie":2001,
    "Memento":2001,
    "The Royal Tenenbaums":2001,
    "Ghost World":2001,
    "Shrek":2001,
    "Harry Potter and the Sorcerer's Stone":2001,
    "Monsters, Inc.":2001,
    "Artificial Intelligence: AI":2001,
    "Pearl Harbor":2001,
    "Kate & Leopold":2001,
    "Vanilla Sky":2001,
    "The Man who Wasn't There":2001,
    "The Affair of the Necklace":2001,
    "Billy Elliot":2000,
    "Before Night Falls":2000,
    "Cast Away":2000,
    "Pollock":2000,
    "Quills":2000,
    "The Contender":2000,
    "Requiem for a Dream":2000,
    "You Can Count on Me":2000,
    "Shadow of the Vampire":2000,
    "Almost Famous":2000,
    "O Brother Where Art Thou?":2000,
    "Wonder Boys":2000,
    "Malena":2000,
    "The Patriot":2000,
    "Meet the Parents":2000,
    "Dancer in the Dark":2000,
    "The Emperor's New Groove":2000,
    "U-571":2000,
    "Space Cowboys":2000,
    "The Perfect Storm":2000,
    "Dr. Seuss' How the Grinch Stole Christmas":2000,
    "Vatel":2000,
    "The Cell":2000,
    "102 Dalmatians":2000,
    "Hollow Man":2000,
    "Being John Malkovich":1999,
    "The Straight Story":1999,
    "Sweet and Lowdown":1999,
    "The Hurricane":1999,
    "Boys Don't Cry":1999,
    "Tumbleweeds":1999,
    "The End of the Affair":1999,
    "Music of the Heart":1999,
    "Magnolia":1999,
    "The Talented Mr. Ripley":1999,
    "Girl, Interrupted":1999,
    "Topsy-Turvy":1999,
    "Election":1999,
    "The Red Violin":1999,
    "Angela's Ashes":1999,
    "Tarzan":1999,
    "South Park: Bigger, Longer & Uncut":1999,
    "Toy Story 2":1999,
    "The Matrix":1999,
    "Fight Club":1999,
    "Star Wars Episode I: The Phantom Menace":1999,
    "The Mummy":1999,
    "Sleepy Hollow":1999,
    "Anna and the King":1999,
    "Snow Falling on Cedars":1999,
    "Austin Powers: The Spy Who Shagged Me":1999,
    "Bicentennial Man":1999,
    "Life":1999,
    "Titus":1999,
    "Stuart Little":1999,
    "The Truman Show":1998,
    "Gods and Monsters":1998,
    "Affliction":1998,
    "American History X":1998,
    "Central Station":1998,
    "One True Thing":1998,
    "Hilary and Jackie":1998,
    "A Civil Action":1998,
    "A Simple Plan":1998,
    "Primary Colors":1998,
    "Little Voice":1998,
    "Bulworth":1998,
    "Out of Sight":1998,
    "Pleasantville":1998,
    "A Bug's Life":1998,
    "Mulan":1998,
    "Patch Adams":1998,
    "The Prince of Egypt":1998,
    "Armageddon":1998,
    "The Mask of Zorro":1998,
    "What Dreams May Come":1998,
    "Beloved":1998,
    "Velvet Goldmine":1998,
    "Mighty Joe Young":1998
};

var bestpic = {
    "name":"bestpic",
    "12 Years a Slave":"nom",
    "Gravity":"nom",
    "Wolf of Wall Street":"nom",
    "American Hustle":"nom",
    "Philomena":"nom",
    "Nebraska":"nom",
    "Captain Phillips":"nom",
    "Dallas Buyers Club":"nom",
    "Her":"nom",
    "Argo":"win",
    "Amour":"nom",
    "Beasts of the Southern Wild":"nom",
    "Django Unchained":"nom",
    "Les Miserables":"nom",
    "Life of Pi":"nom",
    "Lincoln":"nom",
    "Silver Linings Playbook":"nom",
    "Zero Dark Thirty":"nom",
    "The Descendants":"nom",
    "The Artist":"win",
    "Extremely Loud and Incredibly Close":"nom",
    "The Help":"nom",
    "Hugo":"nom",
    "Midnight in Paris":"nom",
    "Moneyball":"nom",
    "The Tree of Life":"nom",
    "War Horse":"nom",
    "The King's Speech":"win",
    "127 Hours":"nom",
    "Black Swan":"nom",
    "The Fighter":"nom",
    "Inception":"nom",
    "The Kids Are All Right":"nom",
    "The Social Network":"nom",
    "Toy Story 3":"nom",
    "True Grit":"nom",
    "Winter's Bone":"nom",
    "The Hurt Locker":"win",
    "Avatar":"nom",
    "The Blind Side":"nom",
    "District 9":"nom",
    "An Education":"nom",
    "Inglourious Basterds":"nom",
    "Precious":"nom",
    "A Serious Man":"nom",
    "Up":"nom",
    "Up in the Air":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "Frost/Nixon":"nom",
    "Milk":"nom",
    "The Reader":"nom",
    "No Country for Old Men":"win",
    "Atonement":"nom",
    "Juno":"nom",
    "Michael Clayton":"nom",
    "There Will Be Blood":"nom",
"Million Dollar Baby":"win","The Lord of the Rings: The Return of the King":"win","Chicago":"win","A Beautiful Mind":"win","Gladiator":"win","American Beauty":"win","Shakespeare in Love":"win","Titanic":"win","The English Patient":"win","Braveheart":"win","Forrest Gump":"win","Schindler's List":"win","Unforgiven":"win","Silence of the Lambs":"win","Dances with Wolves":"win","Driving Miss Daisy":"win","Rain Man":"win","The Last Emperor":"win","Platoon":"win","Out of Africa":"win","Amadeus":"win","Terms of Endearment":"win","Gandhi":"win","Chariots of Fire":"win","Ordinary People":"win","Finding Neverland":"nom","Ray":"nom","Sideways":"nom","The Aviator":"nom","Master and Commander: The Far Side of the World":"nom","Lost in Translation":"nom","Mystic River":"nom","Seabiscuit":"nom","Gangs of New York":"nom","The Hours":"nom","The Lord of the Rings: The Two Towers":"nom","The Pianist":"nom","Moulin Rouge":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","Gosford Park":"nom","In the Bedroom":"nom","Crouching Tiger, Hidden Dragon":"nom","Chocolat":"nom","Erin Brockovich":"nom","Traffic":"nom","The Cider House Rules":"nom","The Green Mile":"nom","The Insider":"nom","The Sixth Sense":"nom","Elizabeth":"nom","Saving Private Ryan":"nom","Life is Beautiful":"nom","The Thin Red Line":"nom","As Good as it Gets":"nom","Good Will Hunting":"nom","L.A. Confidential":"nom","The Full Monty":"nom","Fargo":"nom","Jerry Maguire":"nom","Secrets and Lies":"nom","Shine":"nom","Apollo 13":"nom","Babe":"nom","Sense and Sensibility":"nom","The Postman (Il Postino)":"nom","Four Weddings and a Funeral":"nom","Pulp Fiction":"nom","Quiz Show":"nom","Shawshank Redemption":"nom","In the Name of the Father":"nom","The Fugitive":"nom","The Piano":"nom","The Remains of the Day":"nom","A Few Good Men":"nom","Howard's End":"nom","Scent of a Woman":"nom","The Crying Game":"nom","Beauty and the Beast":"nom","Bugsy":"nom","JFK":"nom","The Prince of Tides":"nom","Awakenings":"nom","Ghost":"nom","Goodfellas":"nom","The Godfather Part III":"nom","Born on the Fourth of July":"nom","Dead Poets Society":"nom","Field of Dreams":"nom","My Left Foot":"nom","Dangerous Liaisons":"nom","Mississippi Burning":"nom","The Accidental Tourist":"nom","Working Girl":"nom","Broadcast News":"nom","Fatal Attraction":"nom","Hope and Glory":"nom","Moonstruck":"nom","A Room with a View":"nom","Children of a Lesser God":"nom","Hannah and her Sisters":"nom","The Mission":"nom","The Color Purple":"nom","Kiss of the Spider Woman":"nom","Prizzi's Honor":"nom","Witness":"nom","A Passage to India":"nom","A Soldier's Story":"nom","Places in the Heart":"nom","The Killing Fields":"nom","Tender Mercies":"nom","The Big Chill":"nom","The Dresser":"nom","The Right Stuff":"nom","E.T.":"nom","Missing":"nom","The Verdict":"nom","Tootsie":"nom","Atlantic City":"nom","On Golden Pond":"nom","Raiders of the Lost Ark":"nom","Reds":"nom","Coal Miner's Daughter":"nom","Raging Bull":"nom","Tess":"nom","The Elephant Man":"nom",
"Crash":"win",
"Brokeback Mountain":"nom",
"Capote":"nom",
"Good Night, and Good Luck":"nom",
"Munich":"nom",
"The Departed":"win",
"Babel":"nom",
"Letters from Iwo Jima":"nom",
"Little Miss Sunshine":"nom",
"The Queen":"nom"
};

var director = {
    "name":"director",
    "American Hustle":"nom",
    "Gravity":"nom",
    "12 Years a Slave":"nom",
    "Nebraska":"nom",
    "Wolf of Wall Street":"nom",
    "Life of Pi":"win",
    "Amour":"nom",
    "Silver Linings Playbook":"nom",
    "Lincoln":"nom",
    "Beasts of the Southern Wild":"nom",
    "The Artist":"win",
    "Midnight in Paris":"nom",
    "The Tree of Life":"nom",
    "The Descendants":"nom",
    "Hugo":"nom",
    "The King's Speech":"win",
    "Black Swan":"nom",
    "True Grit":"nom",
    "The Social Network":"nom",
    "The Fighter":"nom",
    "The Hurt Locker":"win",
    "Avatar":"nom",
    "Precious":"nom",
    "Up in the Air":"nom",
    "Inglourious Basterds":"nom",
    "Slumdog Millionaire":"win",
    "The Reader":"nom",
    "The Curious Case of Benjamin Button":"nom",
    "Frost/Nixon":"nom",
    "Milk":"nom",
    "No Country for Old Men":"win",
    "There Will Be Blood":"nom",
    "Michael Clayton":"nom",
    "Juno":"nom",
"Million Dollar Baby":"win","The Lord of the Rings: The Return of the King":"win","Chicago":"nom","A Beautiful Mind":"win","Gladiator":"nom","American Beauty":"win","Shakespeare in Love":"nom","Titanic":"win","The English Patient":"win","Braveheart":"win","Forrest Gump":"win","Schindler's List":"win","Unforgiven":"win","Silence of the Lambs":"win","Dances with Wolves":"win","Rain Man":"win","The Last Emperor":"win","Platoon":"win","Out of Africa":"win","Amadeus":"win","Terms of Endearment":"win","Gandhi":"win","Chariots of Fire":"nom","Ordinary People":"win","Ray":"nom","Sideways":"nom","The Aviator":"nom","Master and Commander: The Far Side of the World":"nom","Lost in Translation":"nom","Mystic River":"nom","Gangs of New York":"nom","The Hours":"nom","The Pianist":"win","The Lord of the Rings: The Fellowship of the Ring":"nom","Gosford Park":"nom","Crouching Tiger, Hidden Dragon":"nom","Erin Brockovich":"nom","Traffic":"win","The Cider House Rules":"nom","The Insider":"nom","The Sixth Sense":"nom","Saving Private Ryan":"win","Life is Beautiful":"nom","The Thin Red Line":"nom","Good Will Hunting":"nom","L.A. Confidential":"nom","The Full Monty":"nom","Fargo":"nom","Secrets and Lies":"nom","Shine":"nom","Babe":"nom","The Postman (Il Postino)":"nom","Pulp Fiction":"nom","Quiz Show":"nom","In the Name of the Father":"nom","The Piano":"nom","The Remains of the Day":"nom","Howard's End":"nom","Scent of a Woman":"nom","The Crying Game":"nom","Bugsy":"nom","JFK":"nom","Goodfellas":"nom","The Godfather Part III":"nom","Born on the Fourth of July":"win","Dead Poets Society":"nom","My Left Foot":"nom","Mississippi Burning":"nom","Working Girl":"nom","Fatal Attraction":"nom","Hope and Glory":"nom","Moonstruck":"nom","A Room with a View":"nom","Hannah and her Sisters":"nom","The Mission":"nom","Kiss of the Spider Woman":"nom","Prizzi's Honor":"nom","Witness":"nom","A Passage to India":"nom","Places in the Heart":"nom","The Killing Fields":"nom","Tender Mercies":"nom","The Dresser":"nom","E.T.":"nom","The Verdict":"nom","Tootsie":"nom","Atlantic City":"nom","On Golden Pond":"nom","Raiders of the Lost Ark":"nom","Reds":"win","Raging Bull":"nom","Tess":"nom","The Elephant Man":"nom",
"Brokeback Mountain":"win",
"Good Night, and Good Luck":"nom",
"Crash":"nom",
"Capote":"nom",
"Munich":"nom",
"The Departed":"win",
"Letters from Iwo Jima":"nom",
"The Queen":"nom",
"Babel":"nom",
    "The Diving Bell and the Butterfly":"nom",
    "United 93":"nom",
    "Vera Drake":"nom",
    "City of God":"nom",
    "Talk to Her":"nom",
    "Mulholland Dr.":"nom",
    "Black Hawk Down":"nom",
    "Billy Elliot":"nom",
    "Being John Malkovich":"nom",
    "The Truman Show":"nom"
};

var actor = {
    "name":"actor",
    "12 Years a Slave":"nom",
    "Wolf of Wall Street":"nom",
    "American Hustle":"nom",
    "Nebraska":"nom",
    "Dallas Buyers Club":"nom",
    "Lincoln":"win",
    "Silver Linings Playbook":"nom",
    "Les Miserables":"nom",
    "The Artist":"win",
    "The Descendants":"nom",
    "Moneyball":"nom",
    "The King's Speech":"win",
    "True Grit":"nom",
    "The Social Network":"nom",
    "127 Hours":"nom",
    "Up in the Air":"nom",
    "The Hurt Locker":"nom",
    "Milk":"win",
    "Frost/Nixon":"nom",
    "The Curious Case of Benjamin Button":"nom",
    "There Will Be Blood":"win",
    "Michael Clayton":"nom",
"Amadeus":"wn","The Dresser":"nn","Million Dollar Baby":"nom","A Beautiful Mind":"nom","Gladiator":"win","American Beauty":"win","The English Patient":"nom","Forrest Gump":"win","Schindler's List":"nom","Unforgiven":"nom","Silence of the Lambs":"win","Dances with Wolves":"nom","Rain Man":"win","Gandhi":"win","The Aviator":"nom","Gangs of New York":"nom","The Pianist":"win","The Insider":"nom","Saving Private Ryan":"nom","Life is Beautiful":"win","Good Will Hunting":"nom","Shine":"win","Pulp Fiction":"nom","In the Name of the Father":"nom","The Crying Game":"nom","Born on the Fourth of July":"nom","Prizzi's Honor":"nom","Witness":"nom","The Killing Fields":"nom","Tootsie":"nom","On Golden Pond":"win","Reds":"nom","The Elephant Man":"nom","Driving Miss Daisy":"nom","Finding Neverland":"nom","As Good as it Gets":"win","Jerry Maguire":"nom","Shawshank Redemption":"nom","Broadcast News":"nom","Lost in Translation":"nom","Mystic River":"win","The Postman (Il Postino)":"nom","The Remains of the Day":"nom","Scent of a Woman":"win","Bugsy":"nom","Dead Poets Society":"nom","My Left Foot":"win","Kiss of the Spider Woman":"win","Tender Mercies":"win","The Verdict":"nom","Atlantic City":"nom","In the Bedroom":"nom","The Prince of Tides":"nom","Awakenings":"nom","Children of a Lesser God":"nom","Missing":"nom","Ray":"win","Mississippi Burning":"nom","Raging Bull":"win",
"Capote":"win",
"Brokeback Mountain":"nom",
"Good Night, and Good Luck":"nom",
    "The Master":"nom",
    "Flight":"nom",
    "A Better Life":"nom",
    "Tinker Tailor Soldier Spy":"nom",
    "Biutiful":"nom",
    "Crazy Heart":"win",
    "A Single Man":"nom",
    "Invictus":"nom",
    "The Visitor":"nom",
    "The Wrestler":"nom",
    "Sweeney Todd: The Demon Barber of Fleet Street":"nom",
    "In the Valley of Elah":"nom",
    "Eastern Promises":"nom",
    "The Last King of Scotland":"win",
    "Blood Diamond":"nom",
    "Half Nelson":"nom",
    "Venus":"nom",
    "The Pursuit of Happyness":"nom",
    "Hustle & Flow":"nom",
    "Walk the Line":"nom",
    "Hotel Rwanda":"nom",
    "Pirates of the Caribbean: The Curse of the Black Pearl":"nom",
    "House of Sand and Fog":"nom",
    "Cold Mountain":"nom",
    "Adaptation":"nom",
    "The Quiet American":"nom",
    "About Schmidt":"nom",
    "Training Day":"win",
    "I am Sam":"nom",
    "Ali":"nom",
    "Before Night Falls":"nom",
    "Cast Away":"nom",
    "Pollock":"nom",
    "Quills":"nom",
    "The Straight Story":"nom",
    "Sweet and Lowdown":"nom",
    "The Hurricane":"nom",
    "Gods and Monsters":"nom",
    "Affliction":"nom",
    "American History X":"nom"
};

var actress = {
    "name":"actress",
    "Gravity":"nom",
    "American Hustle":"nom",
    "Philomena":"nom",
    "Silver Linings Playbook":"win",
    "Zero Dark Thirty":"nom",
    "Amour":"nom",
    "Beasts of the Southern Wild":"nom",
    "The Help":"nom",
    "Black Swan":"win",
    "The Kids Are All Right":"nom",
    "Winter's Bone":"nom",
    "The Blind Side":"win",
    "An Education":"nom",
    "Precious":"nom",
    "The Reader":"win",
    "Juno":"nom",
"Million Dollar Baby":"win","American Beauty":"nom","The English Patient":"nom","Silence of the Lambs":"win","On Golden Pond":"win","Reds":"nom","Driving Miss Daisy":"win","As Good as it Gets":"win","Broadcast News":"nom","The Remains of the Day":"nom","Atlantic City":"nom","In the Bedroom":"nom","Children of a Lesser God":"win","Missing":"nom","Chicago":"nom","Shakespeare in Love":"win","Out of Africa":"nom","The Hours":"win","Fargo":"win","The Piano":"win","Fatal Attraction":"nom","A Passage to India":"nom","Coal Miner's Daughter":"win","Ordinary People":"nom","Erin Brockovich":"win","Secrets and Lies":"nom","Howard's End":"win","Moonstruck":"win","Places in the Heart":"win","Chocolat":"nom","Sense and Sensibility":"nom","Dangerous Liaisons":"nom","The Color Purple":"nom","Titanic":"nom","Moulin Rouge":"nom","Working Girl":"nom","Elizabeth":"nom","Terms of Endearment":"wn",
"The Queen":"win",
    "The Impossible":"nom",
    "August: Osage County":"nom",
    "Blue Jasmine":"nom",
    "The Iron Lady":"win",
    "Albert Nobbs":"nom",
    "The Girl with the Dragon Tattoo":"nom",
    "My Week with Marilyn":"nom",
    "Rabbit Hole":"nom",
    "Blue Valentine":"nom",
    "The Last Station":"nom",
    "Julie & Julia":"nom",
    "Rachel Getting Married":"nom",
    "Changeling":"nom",
    "Frozen River":"nom",
    "Doubt":"nom",
    "La Vie en Rose":"win",
    "Elizabeth: The Golden Age":"nom",
    "Away from Her":"nom",
    "The Savages":"nom",
    "Volver":"nom",
    "Notes on a Scandal":"nom",
    "The Devil Wears Prada":"nom",
    "Little Children":"nom",
    "Walk the Line":"win",
    "Mrs. Henderson Presents":"nom",
    "Transamerica":"nom",
    "Pride &  Prejudice":"nom",
    "North Country":"nom",
    "Being Julia":"nom",
    "Maria Full of Grace":"nom",
    "Vera Drake":"nom",
    "Eternal Sunshine of the Spotless Mind":"nom",
    "Monster":"win",
    "Whale Rider":"nom",
    "Something's Gotta Give":"nom",
    "In America":"nom",
    "21 Grams":"nom",
    "Frida":"nom",
    "Unfaithful":"nom",
    "Far from Heaven":"nom",
    "Monster's Ball":"win",
    "Iris":"nom",
    "Bridget Jones's Diary":"nom",
    "The Contender":"nom",
    "Requiem for a Dream":"nom",
    "You Can Count on Me":"nom",
    "Boys Don't Cry":"win",
    "Tumbleweeds":"nom",
    "The End of the Affair":"nom",
    "Music of the Heart":"nom",
    "Central Station":"nom",
    "One True Thing":"nom",
    "Hilary and Jackie":"nom"
};

var suppactor = {
    "name":"suppactor",
    "12 Years a Slave":"nom",
    "Wolf of Wall Street":"nom",
    "American Hustle":"nom",
    "Captain Phillips":"nom",
    "Dallas Buyers Club":"nom",
    "Django Unchained":"win",
    "Argo":"nom",
    "Silver Linings Playbook":"nom",
    "Lincoln":"nom",
    "Moneyball":"nom",
    "Extremely Loud and Incredibly Close":"nom",
    "The Fighter":"win",
    "Winter's Bone":"nom",
    "The Kids Are All Right":"nom",
    "The King's Speech":"nom",
    "Inglourious Basterds":"win",
    "Milk":"nom",
    "No Country for Old Men":"win",
    "Michael Clayton":"nom",
"Ordinary People":"wn","Terms of Endearment":"wn","Bugsy":"nn","Platoon":"nn","Million Dollar Baby":"win","Reds":"nom","Driving Miss Daisy":"nom","As Good as it Gets":"nom","Broadcast News":"nom","Chicago":"nom","Shakespeare in Love":"nom","Out of Africa":"nom","The Hours":"nom","Fargo":"nom","Erin Brockovich":"nom","Moonstruck":"nom","Places in the Heart":"nom","Gladiator":"nom","Forrest Gump":"nom","Schindler's List":"nom","Unforgiven":"win","Dances with Wolves":"nom","The Aviator":"nom","Good Will Hunting":"win","Shine":"nom","Pulp Fiction":"nom","In the Name of the Father":"nom","The Crying Game":"nom","Prizzi's Honor":"nom","The Killing Fields":"win","Jerry Maguire":"win","Mystic River":"win","The Verdict":"nom","Raging Bull":"nom","Chariots of Fire":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","Traffic":"win","The Cider House Rules":"win","The Sixth Sense":"nom","Babe":"nom","JFK":"nom","Goodfellas":"win","Hannah and her Sisters":"win","Apollo 13":"nom","Sideways":"nom","Quiz Show":"nom","A Room with a View":"nom","The Green Mile":"nom","A Soldier's Story":"nom","The Godfather Part III":"nom","The Fugitive":"win","A Few Good Men":"nom","The Right Stuff":"nom",
"Crash":"nom",
"Brokeback Mountain":"nom",
"Little Miss Sunshine":"win",
"The Departed":"nom",
    "The Master":"nom",
    "Beginners":"win",
    "My Week with Marilyn":"nom",
    "Warrior":"nom",
    "The Town":"nom",
    "Invictus":"nom",
    "The Messenger":"nom",
    "The Last Station":"nom",
    "The Lovely Bones":"nom",
    "The Dark Knight":"win",
    "Tropic Thunder":"nom",
    "Doubt":"nom",
    "Revolutionary Road":"nom",
    "The Assassination of Jesse James by the Coward Robert Ford":"nom",
    "Charlie Wilson's War":"nom",
    "Into the Wild":"nom",
    "Little Children":"nom",
    "Blood Diamond":"nom",
    "Dreamgirls":"nom",
    "Syriana":"win",
    "Cinderella Man":"nom",
    "A History of Violence":"nom",
    "Collateral":"nom",
    "Closer":"nom",
    "The Cooler":"nom",
    "21 Grams":"nom",
    "In America":"nom",
    "The Last Samurai":"nom",
    "Adaptation":"win",
    "Road to Perdition":"nom",
    "Catch me if you Can":"nom",
    "Iris":"win",
    "Training Day":"nom",
    "Sexy Beast":"nom",
    "Ali":"nom",
    "The Contender":"nom",
    "Shadow of the Vampire":"nom",
    "Magnolia":"nom",
    "The Talented Mr. Ripley":"nom",
    "Affliction":"win",
    "A Civil Action":"nom",
    "The Truman Show":"nom",
    "A Simple Plan":"nom"
    };

var suppactress = {
    "name":"suppactress",
    "12 Years a Slave":"nom",
    "American Hustle":"nom",
    "Nebraska":"nom",
    "Les Miserables":"win",
    "Lincoln":"nom",
    "Silver Linings Playbook":"nom",
    "The Help":"wn",
    "The Artist":"nom",
    "The Fighter":"wn",
    "The King's Speech":"nom",
    "True Grit":"nom",
    "Precious":"win",
    "Up in the Air":"wn",
    "The Curious Case of Benjamin Button":"nom",
    "Michael Clayton":"win",
    "Atonement":"nom",
"Reds":"win","Shakespeare in Love":"win","The Hours":"nom","Moonstruck":"win","Places in the Heart":"nom","Dances with Wolves":"nom","The Aviator":"win","Good Will Hunting":"nom","Pulp Fiction":"nom","In the Name of the Father":"nom","Prizzi's Honor":"win","Mystic River":"nom","Raging Bull":"nom","The Sixth Sense":"nom","Goodfellas":"nom","Hannah and her Sisters":"win","Apollo 13":"nom","Sideways":"nom","A Room with a View":"nom","The English Patient":"win","On Golden Pond":"nom","In the Bedroom":"nom","Children of a Lesser God":"nom","The Piano":"win","Fatal Attraction":"nom","A Passage to India":"win","Secrets and Lies":"nom","Howard's End":"nom","Chocolat":"nom","Sense and Sensibility":"nom","Dangerous Liaisons":"nom","Titanic":"nom","A Beautiful Mind":"win","My Left Foot":"win","The Prince of Tides":"nom","Mississippi Burning":"nom","L.A. Confidential":"win","Ghost":"win","The Accidental Tourist":"win","The Big Chill":"nom","Chicago":"wn","The Color Purple":"nn","Working Girl":"nn","Tootsie":"wn","Gosford Park":"nn",
"Capote":"nom",
"Brokeback Mountain":"nom",
"Babel":"nn",
"Little Miss Sunshine":"nom",
    "The Master":"nom",
    "The Sessions":"nom",
    "August: Osage County":"nom",
    "Blue Jasmine":"nom",
    "Bridesmaids":"nom",
    "Albert Nobbs":"nom",
    "Animal Kingdom":"nom",
    "Nine":"nom",
    "Crazy Heart":"nom",
    "Vicky Cristina Barcelona":"win",
    "Doubt":"nn",
    "The Wrestler":"nom",
    "I'm Not There":"nom",
    "American Gangster":"nom",
    "Gone Baby Gone":"nom",
    "Dreamgirls":"win",
    "Notes on a Scandal":"nom",
    "The Constant Gardener":"win",
    "Junebug":"nom",
    "North Country":"nom",
    "Kinsey":"nom",
    "Hotel Rwanda":"nom",
    "Closer":"nom",
    "Cold Mountain":"win",
    "House of Sand and Fog":"nom",
    "Pieces of April":"nom",
    "Thirteen":"nom",
    "About Schmidt":"nom",
    "Adaptation":"nom",
    "Iris":"nom",
    "Pollock":"win",
    "Almost Famous":"nn",
    "Billy Elliot":"nom",
    "Girl, Interrupted":"win",
    "Being John Malkovich":"nom",
    "Sweet and Lowdown":"nom",
    "Boys Don't Cry":"nom",
    "Primary Colors":"nom",
    "Little Voice":"nom",
    "Hilary and Jackie":"nom",
    "Gods and Monsters":"nom"
};

var screenplay = {
    "name":"screenplay",
    "American Hustle":"nom",
    "Nebraska":"nom",
    "Dallas Buyers Club":"nom",
    "Her":"nom",
    "Django Unchained":"win",
    "Amour":"nom",
    "Zero Dark Thirty":"nom",
    "Midnight in Paris":"win",
    "The Artist":"nom",
    "The King's Speech":"win",
    "The Fighter":"nom",
    "Inception":"nom",
    "The Kids Are All Right":"nom",
    "The Hurt Locker":"win",
    "Inglourious Basterds":"nom",
    "A Serious Man":"nom",
    "Up":"nom",
    "Milk":"win",
    "Juno":"win",
    "Michael Clayton":"nom",
"American Beauty":"win","As Good as it Gets":"nom","Atlantic City":"nom","Braveheart":"nom","Broadcast News":"nom","Bugsy":"nom","Chariots of Fire":"win","Dead Poets Society":"win","E.T.":"nom","Erin Brockovich":"nom","Fargo":"win","Four Weddings and a Funeral":"nom","Gandhi":"win","Gangs of New York":"nom","Ghost":"win","Gladiator":"nom","Good Will Hunting":"win","Gosford Park":"win","Hannah and her Sisters":"win","Hope and Glory":"nom","Jerry Maguire":"nom","Life is Beautiful":"nom","Lost in Translation":"win","Moonstruck":"win","Places in the Heart":"win","Platoon":"nom","Pulp Fiction":"win","Rain Man":"win","Reds":"nom","Saving Private Ryan":"nom","Secrets and Lies":"nom","Shakespeare in Love":"win","Shawshank Redemption":"nom","Shine":"nom","Tender Mercies":"win","The Aviator":"nom","The Big Chill":"nom","The Crying Game":"win","The Full Monty":"nom","The Piano":"win","The Postman (Il Postino)":"nom","The Sixth Sense":"nom","Tootsie":"nom","Unforgiven":"nom","Witness":"win",
"Crash":"win",
"Good Night, and Good Luck":"nom",
"Little Miss Sunshine":"win",
"Babel":"nom",
"Letters from Iwo Jima":"nom",
"The Queen":"nom",
    "12 Years a Slave":"nom",
    "Wolf of Wall Street":"nom",
    "Philomena":"nom",
    "Captain Phillips":"nom",
    "Argo":"win",
    "Beasts of the Southern Wild":"nom",
    "Life of Pi":"nom",
    "Lincoln":"nom",
    "Silver Linings Playbook":"nom",
    "The Descendants":"win",
    "Hugo":"nom",
    "Moneyball":"nom",
    "The Social Network":"win",
    "127 Hours":"nom",
    "Toy Story 3":"nom",
    "True Grit":"nom",
    "Winter's Bone":"nom",
    "Precious":"win",
    "District 9":"nom",
    "An Education":"nom",
    "Up in the Air":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "Frost/Nixon":"nom",
    "The Reader":"nom",
    "No Country for Old Men":"win",
    "Atonement":"nom",
    "There Will Be Blood":"nom",
"Ordinary People":"win","Coal Miner's Daughter":"nom","The Elephant Man":"nom","On Golden Pond":"win","Missing":"win","The Verdict":"nom","Terms of Endearment":"win","The Dresser":"nom","Amadeus":"win","The Killing Fields":"nom","A Passage to India":"nom","A Soldier's Story":"nom","Out of Africa":"win","The Color Purple":"nom","Kiss of the Spider Woman":"nom","Prizzi's Honor":"nom","A Room with a View":"win","Children of a Lesser God":"nom","The Last Emperor":"win","Fatal Attraction":"nom","Dangerous Liaisons":"win","The Accidental Tourist":"nom","Driving Miss Daisy":"win","Born on the Fourth of July":"nom","Field of Dreams":"nom","My Left Foot":"nom","Dances with Wolves":"win","Awakenings":"nom","Goodfellas":"nom","Silence of the Lambs":"win","JFK":"nom","The Prince of Tides":"nom","Howard's End":"win","Scent of a Woman":"nom","Schindler's List":"win","In the Name of the Father":"nom","The Remains of the Day":"nom","Forrest Gump":"win","Quiz Show":"nom","Sense and Sensibility":"win","Apollo 13":"nom","Babe":"nom","The English Patient":"nom","L.A. Confidential":"win","The Thin Red Line":"nom","The Cider House Rules":"win","The Green Mile":"nom","The Insider":"nom","Traffic":"win","Chocolat":"nom","Crouching Tiger, Hidden Dragon":"nom","A Beautiful Mind":"win","In the Bedroom":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","The Pianist":"win","Chicago":"nom","The Hours":"nom","The Lord of the Rings: The Return of the King":"win","Mystic River":"nom","Seabiscuit":"nom","Sideways":"win","Finding Neverland":"nom","Million Dollar Baby":"nom",
"Brokeback Mountain":"win",
"Capote":"nom",
"Munich":"nom",
"The Departed":"win",
    "Flight":"nom",
    "Moonrise Kingdom":"nom",
    "Blue Jasmine":"nom",
    "Before Midnight":"nom",
    "Bridesmaids":"nom",
    "Margin Call":"nom",
    "A Separation":"nom",
    "The Ides of March":"nom",
    "Tinker Tailor Soldier Spy":"nom",
    "Another Year":"nom",
    "The Messenger":"nom",
    "In the Loop":"nom",
    "Frozen River":"nom",
    "Happy-Go-Lucky":"nom",
    "In Bruges":"nom",
    "WALL-E":"nom",
    "Doubt":"nom",
    "Lars and the Real Girl":"nom",
    "Ratatouille":"nom",
    "The Savages":"nom",
    "Away from Her":"nom",
    "The Diving Bell and the Butterfly":"nom",
    "Pan's Labyrinth":"nom",
    "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan":"nom",
    "Children of Men":"nom",
    "Little Children":"nom",
    "Notes on a Scandal":"nom",
    "Match Point":"nom",
    "The Squid and the Whale":"nom",
    "Syriana":"nom",
    "The Constant Gardener":"nom",
    "A History of Violence":"nom",
    "Eternal Sunshine of the Spotless Mind":"win",
    "Hotel Rwanda":"nom",
    "The Incredibles":"nom",
    "Vera Drake":"nom",
    "The Motorcycle Diaries":"nom",
    "Before Sunset":"nom",
    "Dirty Pretty Things":"nom",
    "Finding Nemo":"nom",
    "In America":"nom",
    "The Barbarian Invasions":"nom",
    "American Splendor":"nom",
    "City of God":"nom",
    "Talk to Her":"win",
    "Far from Heaven":"nom",
    "My Big Fat Greek Wedding":"nom",
    "Y tu Mama Tambien":"nom",
    "About a Boy":"nom",
    "Adaptation":"nom",
    "Amelie":"nom",
    "Memento":"nom",
    "Monster's Ball":"nom",
    "The Royal Tenenbaums":"nom",
    "Ghost World":"nom",
    "Shrek":"nom",
    "Almost Famous":"win",
    "Billy Elliot":"nom",
    "You Can Count on Me":"nom",
    "O Brother Where Art Thou?":"nom",
    "Wonder Boys":"nom",
    "Being John Malkovich":"nom",
    "Magnolia":"nom",
    "Topsy-Turvy":"nom",
    "Election":"nom",
    "The Talented Mr. Ripley":"nom",
    "Bulworth":"nom",
    "The Truman Show":"nom",
    "Gods and Monsters":"win",
    "Out of Sight":"nom",
    "Primary Colors":"nom",
    "A Simple Plan":"nom"
    };

var filmediting = {
    "name":"filmediting",
    "12 Years a Slave":"nom",
    "Gravity":"nom",
    "American Hustle":"nom",
    "Captain Phillips":"nom",
    "Dallas Buyers Club":"nom",
    "Argo":"win",
    "Life of Pi":"nom",
    "Lincoln":"nom",
    "Silver Linings Playbook":"nom",
    "Zero Dark Thirty":"nom",
    "The Artist":"nom",
    "The Descendants":"nom",
    "Hugo":"nom",
    "Moneyball":"nom",
    "The Social Network":"win",
    "127 Hours":"nom",
    "Black Swan":"nom",
    "The Fighter":"nom",
    "The King's Speech":"nom",
    "The Hurt Locker":"win",
    "Avatar":"nom",
    "District 9":"nom",
    "Inglourious Basterds":"nom",
    "Precious":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "Frost/Nixon":"nom",
    "Milk":"nom",
    "No Country for Old Men":"nom",
    "There Will Be Blood":"nom",
"Million Dollar Baby":"nom","The Lord of the Rings: The Return of the King":"win","Chicago":"win","A Beautiful Mind":"nom","Gladiator":"nom","American Beauty":"nom","Shakespeare in Love":"nom","Titanic":"win","The English Patient":"win","Braveheart":"nom","Forrest Gump":"win","Schindler's List":"win","Unforgiven":"win","Silence of the Lambs":"nom","Dances with Wolves":"win","Rain Man":"nom","The Last Emperor":"win","Platoon":"win","Out of Africa":"nom","Amadeus":"nom","Terms of Endearment":"nom","Gandhi":"win","Chariots of Fire":"nom","Ray":"nom","The Aviator":"win","Master and Commander: The Far Side of the World":"nom","Gangs of New York":"nom","The Hours":"nom","The Pianist":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","Crouching Tiger, Hidden Dragon":"nom","Traffic":"win","The Cider House Rules":"nom","The Insider":"nom","The Sixth Sense":"nom","Saving Private Ryan":"win","Life is Beautiful":"nom","The Thin Red Line":"nom","Good Will Hunting":"nom","L.A. Confidential":"nom","Fargo":"nom","Shine":"nom","Babe":"nom","Pulp Fiction":"nom","In the Name of the Father":"nom","The Piano":"nom","The Crying Game":"nom","JFK":"win","Goodfellas":"nom","The Godfather Part III":"nom","Born on the Fourth of July":"win","Mississippi Burning":"nom","Fatal Attraction":"nom","Hannah and her Sisters":"nom","The Mission":"nom","Prizzi's Honor":"nom","Witness":"win","A Passage to India":"nom","The Killing Fields":"win","E.T.":"nom","Tootsie":"nom","On Golden Pond":"nom","Raiders of the Lost Ark":"win","Reds":"nom","Raging Bull":"win","The Elephant Man":"nom","Driving Miss Daisy":"nom","Finding Neverland":"nom","Seabiscuit":"nom","The Lord of the Rings: The Two Towers":"nom","Moulin Rouge":"nom","As Good as it Gets":"nom","Jerry Maguire":"nom","Apollo 13":"win","Shawshank Redemption":"nom","The Fugitive":"nom","A Few Good Men":"nom","Ghost":"nom","Broadcast News":"nom","The Right Stuff":"win","Coal Miner's Daughter":"nom",
"Crash":"win",
"Munich":"nom",
"The Departed":"win",
"Babel":"nom",
    "The Girl with the Dragon Tattoo":"win",
    "The Dark Knight":"nom",
    "The Bourne Ultimatum":"win",
    "The Diving Bell and the Butterfly":"nom",
    "Into the Wild":"nom",
    "Children of Men":"nom",
    "United 93":"nom",
    "Blood Diamond":"nom",
    "Cinderella Man":"nom",
    "The Constant Gardener":"nom",
    "Walk the Line":"nom",
    "Collateral":"nom",
    "City of God":"nom",
    "Cold Mountain":"nom",
    "Black Hawk Down":"win",
    "Memento":"nom",
    "Almost Famous":"nom",
    "Wonder Boys":"nom",
    "The Matrix":"win",
    "Out of Sight":"nom"
};

var productiondesign = {
    "name":"productiondesign",
    "12 Years a Slave":"nom",
    "Gravity":"nom",
    "American Hustle":"nom",
    "Her":"nom",
    "Lincoln":"win",
    "Les Miserables":"nom",
    "Life of Pi":"nom",
    "Hugo":"win",
    "The Artist":"nom",
    "Midnight in Paris":"nom",
    "War Horse":"nom",
    "Inception":"nom",
    "The King's Speech":"nom",
    "True Grit":"nom",
    "Avatar":"win",
    "The Curious Case of Benjamin Button":"win",
    "Atonement":"nom",
    "There Will Be Blood":"nom",
"Reds":"nom","Shakespeare in Love":"win","Dances with Wolves":"nom","The Aviator":"win","A Room with a View":"win","The English Patient":"win","A Passage to India":"nom","Howard's End":"win","Titanic":"win","The Prince of Tides":"nom","L.A. Confidential":"nom","Chicago":"win","The Color Purple":"nom","Bugsy":"win","Out of Africa":"win","Gladiator":"nom","Forrest Gump":"nom","Schindler's List":"win","Unforgiven":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","The Godfather Part III":"nom","The Right Stuff":"nom","Coal Miner's Daughter":"nom","Moulin Rouge":"win","Elizabeth":"nom","Amadeus":"win","Rain Man":"nom","Gandhi":"win","Gangs of New York":"nom","Saving Private Ryan":"nom","Witness":"nom","The Last Emperor":"win","Crouching Tiger, Hidden Dragon":"win","Seabiscuit":"nom","Hope and Glory":"nom","Master and Commander: The Far Side of the World":"nom","The Mission":"nom","Raiders of the Lost Ark":"win","Tess":"win","Hannah and her Sisters":"nom","Apollo 13":"nom","Dangerous Liaisons":"win","Gosford Park":"nom","Terms of Endearment":"nom","Driving Miss Daisy":"nom","The Cider House Rules":"nom","Babe":"nom","The Remains of the Day":"nom","The Elephant Man":"nom","Finding Neverland":"nom","The Lord of the Rings: The Return of the King":"win","The Lord of the Rings: The Two Towers":"nom",
"Good Night, and Good Luck":"nom",
    "Anna Karenina":"nom",
    "The Hobbit: An Unexpected Journey":"nom",
    "The Great Gatsby":"nom",
    "Harry Potter and the Deathly Hallows: Part 2":"nom",
    "Alice in Wonderland":"nom",
    "Harry Potter and the Deathly Hallows: Part 1":"nom",
    "The Imaginarium of Dr. Parnassus":"nom",
    "Nine":"nom",
    "Sherlock Holmes":"nom",
    "The Young Victoria":"nom",
    "Changeling":"nom",
    "The Dark Knight":"nom",
    "The Duchess":"nom",
    "Revolutionary Road":"nom",
    "Sweeney Todd: The Demon Barber of Fleet Street":"win",
    "American Gangster":"nom",
    "The Golden Compass":"nom",
    "Pan's Labyrinth":"win",
    "Dreamgirls":"nom",
    "The Good Shepherd":"nom",
    "Pirates of the Caribbean: Dead Man's Chest":"nom",
    "The Prestige":"nom",
    "Memoirs of a Geisha":"win",
    "Harry Potter and the Goblet of Fire":"nom",
    "King Kong":"nom",
    "Pride &  Prejudice":"nom",
    "A Very Long Engagement":"nom",
    "The Phantom of the Opera":"nom",
    "Lemony Snicket's A Series of Unfortunate Events":"nom",
    "Girl with a Pearl Earring":"nom",
    "The Last Samurai":"nom",
    "Frida":"nom",
    "Road to Perdition":"nom",
    "Amelie":"nom",
    "Harry Potter and the Sorcerer's Stone":"nom",
    "Dr. Seuss' How the Grinch Stole Christmas":"nom",
    "Quills":"nom",
    "Vatel":"nom",
    "Sleepy Hollow":"win",
    "Anna and the King":"nom",
    "The Talented Mr. Ripley":"nom",
    "Topsy-Turvy":"nom",
    "Pleasantville":"nom",
    "What Dreams May Come":"nom"
};

var cinematography = {
    "name":"cinematography",
    "Gravity":"nom",
    "Nebraska":"nom",
    "Life of Pi":"win",
    "Django Unchained":"nom",
    "Lincoln":"nom",
    "Hugo":"win",
    "The Artist":"nom",
    "The Tree of Life":"nom",
    "War Horse":"nom",
    "Inception":"win",
    "Black Swan":"nom",
    "The King's Speech":"nom",
    "The Social Network":"nom",
    "True Grit":"nom",
    "Avatar":"win",
    "The Hurt Locker":"nom",
    "Inglourious Basterds":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "The Reader":"nom",
    "There Will Be Blood":"win",
    "Atonement":"nom",
    "No Country for Old Men":"nom",
"Reds":"win","Shakespeare in Love":"nom","Dances with Wolves":"win","The Aviator":"win","Raging Bull":"nom","A Room with a View":"nom","The English Patient":"win","On Golden Pond":"nom","The Piano":"nom","A Passage to India":"nom","Howard's End":"nom","Sense and Sensibility":"nom","Titanic":"win","The Prince of Tides":"nom","Mississippi Burning":"win","L.A. Confidential":"nom","Chicago":"nom","The Color Purple":"nom","Tootsie":"nom","Bugsy":"nom","Platoon":"nom","Broadcast News":"nom","Out of Africa":"win","Fargo":"nom","Gladiator":"nom","Forrest Gump":"nom","Schindler's List":"win","Unforgiven":"nom","The Killing Fields":"win","The Lord of the Rings: The Fellowship of the Ring":"win","JFK":"win","The Godfather Part III":"nom","The Fugitive":"nom","The Right Stuff":"nom","American Beauty":"win","Coal Miner's Daughter":"nom","Moulin Rouge":"nom","Elizabeth":"nom","Amadeus":"nom","Rain Man":"nom","Gandhi":"win","Gangs of New York":"nom","The Pianist":"nom","The Insider":"nom","Saving Private Ryan":"win","Born on the Fourth of July":"nom","Witness":"nom","Shawshank Redemption":"nom","Braveheart":"win","The Last Emperor":"win","Crouching Tiger, Hidden Dragon":"win","The Thin Red Line":"nom","E.T.":"nom","Seabiscuit":"nom","Hope and Glory":"nom","Master and Commander: The Far Side of the World":"win","The Mission":"win","Raiders of the Lost Ark":"nom","Tess":"win",
"Brokeback Mountain":"nom",
"Good Night, and Good Luck":"nom",
    "Anna Karenina":"nom",
    "Skyfall":"nom",
    "The Grandmaster":"nom",
    "Inside Llewyn Davis":"nom",
    "Prisoners":"nom",
    "The Girl with the Dragon Tattoo":"nom",
    "Harry Potter and the Half-Blood Prince":"nom",
    "The White Ribbon":"nom",
    "Changeling":"nom",
    "The Dark Knight":"nom",
    "The Assassination of Jesse James by the Coward Robert Ford":"nom",
    "The Diving Bell and the Butterfly":"nom",
    "Pan's Labyrinth":"win",
    "The Black Dahlia":"nom",
    "Children of Men":"nom",
    "The Illusionist":"nom",
    "The Prestige":"nom",
    "Memoirs of a Geisha":"win",
    "Batman Begins":"nom",
    "The New World":"nom",
    "A Very Long Engagement":"nom",
    "The Passion of the Christ":"nom",
    "The Phantom of the Opera":"nom",
    "House of Flying Daggers":"nom",
    "City of God":"nom",
    "Girl with a Pearl Earring":"nom",
    "Cold Mountain":"nom",
    "Road to Perdition":"win",
    "Far from Heaven":"nom",
    "Amelie":"nom",
    "Black Hawk Down":"nom",
    "The Man who Wasn't There":"nom",
    "Malena":"nom",
    "O Brother Where Art Thou?":"nom",
    "The Patriot":"nom",
    "The End of the Affair":"nom",
    "Sleepy Hollow":"nom",
    "Snow Falling on Cedars":"nom",
    "A Civil Action":"nom"
};

var score = {
    "name":"score",
    "Gravity":"nom",
    "Philomena":"nom",
    "Her":"nom",
    "Life of Pi":"win",
    "Argo":"nom",
    "Lincoln":"nom",
    "The Artist":"win",
    "Hugo":"nom",
    "War Horse":"nom",
    "The Social Network":"win",
    "127 Hours":"nom",
    "Inception":"nom",
    "The King's Speech":"nom",
    "Up":"win",
    "Avatar":"nom",
    "The Hurt Locker":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "Milk":"nom",
    "Atonement":"win",
    "Michael Clayton":"nom",
"Shakespeare in Love":"win",
    "Dances with Wolves":"win",
    "The English Patient":"win",
    "A Passage to India":"win",
    "Howard's End":"nom","Titanic":"win",
    "The Prince of Tides":"nom",
    "L.A. Confidential":"nom",
    "The Color Purple":"nom",
    "Bugsy":"nom",
    "Out of Africa":"win",
    "Gladiator":"nom",
    "Forrest Gump":"nom",
    "Schindler's List":"win",
    "The Lord of the Rings: The Fellowship of the Ring":"win",
    "The Right Stuff":"win",
    "Elizabeth":"nom",
    "Rain Man":"nom",
    "Gandhi":"nom",
    "Saving Private Ryan":"nom",
    "Witness":"nom",
    "The Last Emperor":"win",
    "Crouching Tiger, Hidden Dragon":"win",
    "The Mission":"nom",
    "Raiders of the Lost Ark":"nom",
    "Tess":"nom","Apollo 13":"nom",
    "Dangerous Liaisons":"nom",
    "Terms of Endearment":"nom",
    "The Cider House Rules":"nom",
    "The Remains of the Day":"nom",
    "The Elephant Man":"nom","Finding Neverland":"win",
    "The Lord of the Rings: The Return of the King":"win",
    "On Golden Pond":"nom",
    "Sense and Sensibility":"nom",
    "JFK":"nom",
    "The Fugitive":"nom",
    "American Beauty":"nom",
    "Born on the Fourth of July":"nom",
    "Shawshank Redemption":"nom",
    "Braveheart":"nom",
    "The Thin Red Line":"nom",
    "E.T.":"win",
    "The Hours":"nom",
    "Good Will Hunting":"nom",
    "Chocolat":"nom",
    "A Beautiful Mind":"nom",
    "Ghost":"nom",
    "The Accidental Tourist":"nom",
    "As Good as it Gets":"nom",
    "Shine":"nom",
    "Chariots of Fire":"win",
    "Life is Beautiful":"win",
    "The Postman (Il Postino)":"nom",
    "The Full Monty":"nom",
    "Field of Dreams":"nom",
    "Beauty and the Beast":"win",
"Brokeback Mountain":"win",
"Munich":"nom",
"Babel":"win",
"The Queen":"nom",
    "Anna Karenina":"nom",
    "Skyfall":"nom",
    "The Book Thief":"nom",
    "Saving Mr. Banks":"nom",
    "The Adventures of Tintin":"nom",
    "Tinker Tailor Soldier Spy":"nom",
    "How to Train your Dragon":"nom",
    "Fantastic Mr. Fox":"nom",
    "Sherlock Holmes":"nom",
    "Defiance":"nom",
    "WALL-E":"nom",
    "The Kite Runner":"nom",
    "Ratatouille":"nom",
    "3:10 to Yuma":"nom",
    "The Good German":"nom",
    "Notes on a Scandal":"nom",
    "Pan's Labyrinth":"nom",
    "The Constant Gardener":"nom",
    "Memoirs of a Geisha":"nom",
    "Pride &  Prejudice":"nom",
    "The Village":"nom",
    "The Passion of the Christ":"nom",
    "Harry Potter and the Prisoner of Azkaban":"nom",
    "Lemony Snicket's A Series of Unfortunate Events":"nom",
    "Big Fish":"nom",
    "Cold Mountain":"nom",
    "House of Sand and Fog":"nom",
    "Finding Nemo":"nom",
    "Frida":"win",
    "Catch me if you Can":"nom",
    "Far from Heaven":"nom",
    "Road to Perdition":"nom",
    "Harry Potter and the Sorcerer's Stone":"nom",
    "Monsters, Inc.":"nom",
    "Artificial Intelligence: AI":"nom",
    "Malena":"nom",
    "The Patriot":"nom",
    "The Red Violin":"win",
    "Angela's Ashes":"nom",
    "The Talented Mr. Ripley":"nom",
    "Pleasantville":"nom",
    "A Bug's Life":"nom",
    "Mulan":"nom",
    "Patch Adams":"nom",
    "The Prince of Egypt":"nom"
};

var song = {
    "name":"song",
    "Her":"nom",
    "Life of Pi":"win",
    "Les Miserables":"nom",
    "Toy Story 3":"win",
    "127 Hours":"nom",
    "Slumdog Millionaire":"wn",
"Tootsie":"nom",
"Tender Mercies":"nom",
"The Color Purple":"nom",
"The Godfather Part III":"nom",
"Beauty and the Beast":"wnn",
"Titanic":"win",
"Good Will Hunting":"nom",
"Crouching Tiger, Hidden Dragon":"nom",
"The Lord of the Rings: The Fellowship of the Ring":"nom",
"Chicago":"nom",
"Gangs of New York":"nom",
"The Lord of the Rings: The Return of the King":"win",
"Crash":"nom",
    "Skyfall":"win",
    "Chasing Ice":"nom",
    "Ted":"nom",
    "Despicable Me 2":"nom",
    "Frozen":"nom",
    "Mandela: Long Walk to Freedom":"nom",
    "The Muppets":"win",
    "Rio":"nom",
    "Country Strong":"nom",
    "Tangled":"nom",
    "Crazy Heart":"win",
    "The Princess and the Frog":"nn",
    "Paris 36":"nom",
    "Nine":"nom",
    "WALL-E":"nom",
    "Once":"win",
    "Enchanted":"nnn",
    "August Rush":"nom",
    "An Inconvenient Truth":"win",
    "Dreamgirls":"nnn",
    "Cars":"nom",
    "Hustle & Flow":"win",
    "Transamerica":"nom",
    "The Motorcycle Diaries":"win",
    "The Phantom of the Opera":"nom",
    "The Polar Express":"nom",
    "The Chorus":"nom",
    "Shrek 2":"nom",
    "A Mighty Wind":"nom",
    "Cold Mountain":"nn",
    "The Triplets of Belleville":"nom",
    "8 Mile":"win",
    "Frida":"nom",
    "The Wild Thornberrys Movie":"nom",
    "Monsters, Inc.":"win",
    "Pearl Harbor":"nom",
    "Kate & Leopold":"nom",
    "Vanilla Sky":"nom",
    "Wonder Boys":"win",
    "Meet the Parents":"nom",
    "Dancer in the Dark":"nom",
    "The Emperor's New Groove":"nom",
    "Tarzan":"win",
    "South Park: Bigger, Longer & Uncut":"nom",
    "Music of the Heart":"nom",
    "Magnolia":"nom",
    "Toy Story 2":"nom"
};

var soundmixing = {
    "name":"soundmixing",
    "Gravity":"nom",
    "Captain Phillips":"nom",
    "Les Miserables":"win",
    "Argo":"nom",
    "Life of Pi":"nom",
    "Lincoln":"nom",
    "Hugo":"win",
    "Moneyball":"nom",
    "War Horse":"nom",
    "The Hurt Locker":"win",
    "Avatar":"nom",
    "Inglourious Basterds":"nom",
    "Slumdog Millionaire":"win",
    "The Curious Case of Benjamin Button":"nom",
    "No Country for Old Men":"nom",
"Coal Miner's Daughter":"nom",
"Raging Bull":"nom",
"On Golden Pond":"nom",
"Reds":"nom",
"E.T.":"win",
"Gandhi":"nom",
"Tootsie":"nom",
"The Right Stuff":"win",
"Terms of Endearment":"nom",
"Amadeus":"win",
"A Passage to India":"nom",
"Out of Africa":"win",
"Platoon":"win",
"The Last Emperor":"win",
"Mississippi Burning":"nom",
"Born on the Fourth of July":"nom",
"Dances with Wolves":"win",
"Beauty and the Beast":"nom",
"JFK":"nom",
"Silence of the Lambs":"nom",
"Unforgiven":"nom",
"A Few Good Men":"nom",
"The Fugitive":"nom",
"Schindler's List":"nom",
"Forrest Gump":"nom",
"Apollo 13":"win",
"Braveheart":"nom",
"The English Patient":"win",
"Titanic":"win",
"L.A. Confidential":"nom",
"Saving Private Ryan":"win",
"Shakespeare in Love":"nom",
"The Thin Red Line":"nom",
"The Green Mile":"nom",
"Gladiator":"win",
"The Lord of the Rings: The Fellowship of the Ring":"nom",
"Moulin Rouge":"nom",
"Chicago":"win",
"Gangs of New York":"nom",
"The Lord of the Rings: The Two Towers":"nom",
"The Lord of the Rings: The Return of the King":"win",
"Master and Commander: The Far Side of the World":"nom",
"Seabiscuit":"nom",
"Ray":"win",
"The Aviator":"nom",
    "Skyfall":"nom",
    "The Hobbit: The Desolation of Smaug":"nom",
    "Inside Llewyn Davis":"nom",
    "Lone Survivor":"nom",
    "The Girl with the Dragon Tattoo":"nom",
    "Transformers: Dark of the Moon":"nom",
    "Salt":"nom",
    "Inception":"win",
    "The King's Speech":"nom",
    "The Social Network":"nom",
    "True Grit":"nom",
    "Star Trek":"nom",
    "Transformers: Revenge of the Fallen":"nom",
    "The Dark Knight":"nom",
    "WALL-E":"nom",
    "Wanted":"nom",
    "The Bourne Ultimatum":"win",
    "Ratatouille":"nom",
    "3:10 to Yuma":"nom",
    "Transformers":"nom",
    "Dreamgirls":"win",
    "Apocalypto":"nom",
    "Blood Diamond":"nom",
    "Flags of our Fathers":"nom",
    "Pirates of the Caribbean: Dead Man's Chest":"nom",
    "King Kong":"win",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe":"nom",
    "Memoirs of a Geisha":"nom",
    "Walk the Line":"nom",
    "War of the Worlds":"nom",
    "The Incredibles":"nom",
    "Spider-Man 2":"nom",
    "The Polar Express":"nom",
    "The Last Samurai":"nom",
    "Pirates of the Caribbean: The Curse of the Black Pearl":"nom",
    "Road to Perdition":"nom",
    "Spider-Man":"nom",
    "Black Hawk Down":"win",
    "Amelie":"nom",
    "Pearl Harbor":"nom",
    "Cast Away":"nom",
    "The Patriot":"nom",
    "The Perfect Storm":"nom",
    "U-571":"nom",
    "The Matrix":"win",
    "The Mummy":"nom",
    "Star Wars Episode I: The Phantom Menace":"nom",
    "The Insider":"nom",
    "Armageddon":"nom",
    "The Mask of Zorro":"nom"
};

var soundediting = {
    "name":"soundediting",
    "Gravity":"nom",
    "Captain Phillips":"nom",
    "Zero Dark Thirty":"nom",
    "Argo":"nom",
    "Django Unchained":"nom",
    "Life of Pi":"nom",
    "Hugo":"win",
    "War Horse":"nom",
    "The Hurt Locker":"win",
    "Avatar":"nom",
    "Inglourious Basterds":"nom",
    "Up":"nom",
    "Slumdog Millionaire":"nom",
    "No Country for Old Men":"nom",
    "There Will Be Blood":"nom",
"E.T.":"win",
"The Right Stuff":"win",
"The Fugitive":"nom",
"Forrest Gump":"nom",
"Braveheart":"win",
"Titanic":"win",
"Saving Private Ryan":"win",
"The Lord of the Rings: The Two Towers":"win",
"Master and Commander: The Far Side of the World":"win",
"Letters from Iwo Jima":"win",
    "Skyfall":"win",
    "All is Lost":"nom",
    "The Hobbit: The Desolation of Smaug":"nom",
    "Lone Survivor":"nom",
    "Drive":"nom",
    "The Girl with the Dragon Tattoo":"nom",
    "Transformers: Dark of the Moon":"nom",
    "Tron: Legacy":"nom",
    "Unstoppable":"nom",
    "Inception":"win",
    "Toy Story 3":"nom",
    "True Grit":"nom",
    "Star Trek":"nom",
    "The Dark Knight":"win",
    "Iron Man":"nom",
    "WALL-E":"nom",
    "Wanted":"nom",
    "The Bourne Ultimatum":"win",
    "Ratatouille":"nom",
    "Transformers":"nom",
    "Apocalypto":"nom",
    "Blood Diamond":"nom",
    "Flags of our Fathers":"nom",
    "Pirates of the Caribbean: Dead Man's Chest":"nom",
    "King Kong":"win",
    "Memoirs of a Geisha":"nom",
    "War of the Worlds":"nom",
    "The Incredibles":"win",
    "Spider-Man 2":"nom",
    "The Polar Express":"nom",
    "Pirates of the Caribbean: The Curse of the Black Pearl":"nom",
    "Finding Nemo":"nom",
    "Minority Report":"nom",
    "Road to Perdition":"nom",
    "Pearl Harbor":"win",
    "Monsters, Inc.":"nom",
    "U-571":"win",
    "Space Cowboys":"nom",
    "The Matrix":"win",
    "Fight Club":"nom",
    "Star Wars Episode I: The Phantom Menace":"nom",
    "Armageddon":"nom",
    "The Mask of Zorro":"nom"
};

var costumes = {
    "name":"costumes",
    "12 Years a Slave":"nom",
    "American Hustle":"nom",
    "Les Miserables":"nom",
    "Lincoln":"nom",
    "The Artist":"win",
    "Hugo":"nom",
    "The King's Speech":"nom",
    "True Grit":"nom",
    "The Curious Case of Benjamin Button":"nom",
    "Milk":"nom",
    "Atonement":"nom",
"Shakespeare in Love":"win","Dances with Wolves":"nom","The English Patient":"win","A Passage to India":"nom","Howard's End":"nom","Titanic":"win","The Color Purple":"nom","Bugsy":"win","Out of Africa":"nom","Gladiator":"win","Schindler's List":"nom","The Lord of the Rings: The Fellowship of the Ring":"nom","Elizabeth":"nom","Gandhi":"win","The Last Emperor":"win","Crouching Tiger, Hidden Dragon":"nom","The Mission":"nom","Tess":"win","Dangerous Liaisons":"win","The Remains of the Day":"nom","The Elephant Man":"nom","Finding Neverland":"nom","The Lord of the Rings: The Return of the King":"win","Sense and Sensibility":"nom","Braveheart":"nom","The Hours":"nom","Chariots of Fire":"win","Reds":"nom","The Aviator":"win","A Room with a View":"win","Chicago":"win","Moulin Rouge":"win","Amadeus":"win","Gangs of New York":"nom","Seabiscuit":"nom","Master and Commander: The Far Side of the World":"nom","Gosford Park":"nom","Driving Miss Daisy":"nom","The Piano":"nom","The Pianist":"nom","Places in the Heart":"nom","Prizzi's Honor":"nom","Ray":"nom",
"The Queen":"nom",
    "Anna Karenina":"win",
    "Mirror Mirror":"nom",
    "Snow White and the Huntsman":"nom",
    "The Grandmaster":"nom",
    "The Great Gatsby":"nom",
    "The Invisible Woman":"nom",
    "Anonymous":"nom",
    "Jane Eyre":"nom",
    "W.E.":"nom",
    "Alice in Wonderland":"nom",
    "I am Love":"nom",
    "The Tempest":"nom",
    "The Young Victoria":"win",
    "Bright Star":"nom",
    "Coco Before Chanel":"nom",
    "The Imaginarium of Dr. Parnassus":"nom",
    "Nine":"nom",
    "The Duchess":"win",
    "Australia":"nom",
    "Revolutionary Road":"nom",
    "Elizabeth: The Golden Age":"win",
    "Across the Universe":"nom",
    "La Vie en Rose":"nom",
    "Sweeney Todd: The Demon Barber of Fleet Street":"nom",
    "Marie Antoinette":"win",
    "Curse of the Golden Flower":"nom",
    "The Devil Wears Prada":"nom",
    "Dreamgirls":"nom",
    "Memoirs of a Geisha":"win",
    "Charlie and the Chocolate Factory":"nom",
    "Mrs. Henderson Presents":"nom",
    "Pride &  Prejudice":"nom",
    "Walk the Line":"nom",
    "Troy":"nom",
    "Lemony Snicket's A Series of Unfortunate Events":"nom",
    "Girl with a Pearl Earring":"nom",
    "The Last Samurai":"nom",
    "Frida":"nom",
    "The Affair of the Necklace":"nom",
    "Harry Potter and the Sorcerer's Stone":"nom",
    "Dr. Seuss' How the Grinch Stole Christmas":"nom",
    "102 Dalmatians":"nom",
    "Quills":"nom",
    "Topsy-Turvy":"win",
    "Anna and the King":"nom",
    "Sleepy Hollow":"nom",
    "The Talented Mr. Ripley":"nom",
    "Titus":"nom",
    "Beloved":"nom",
    "Pleasantville":"nom",
    "Velvet Goldmine":"nom"
};

var makeup = {
    "name":"makeup",
    "Dallas Buyers Club":"nom",
    "Les Miserables":"win",
    "The Curious Case of Benjamin Button":"win",
"Shakespeare in Love":"nom","Titanic":"nom","The Color Purple":"nom","Schindler's List":"nom","The Lord of the Rings: The Fellowship of the Ring":"win","Elizabeth":"win","Gandhi":"nom","The Lord of the Rings: The Return of the King":"win","Braveheart":"win","Moulin Rouge":"nom","Amadeus":"win","Master and Commander: The Far Side of the World":"nom","Driving Miss Daisy":"win","Forrest Gump":"nom","Saving Private Ryan":"nom","A Beautiful Mind":"nom",
    "Hitchcock":"nom",
    "The Hobbit: An Unexpected Journey":"nom",
    "Bad Grandpa":"nom",
    "The Lone Ranger":"nom",
    "The Iron Lady":"win",
    "Albert Nobbs":"nom",
    "Harry Potter and the Deathly Hallows: Part 2":"nom",
    "The Wolfman":"win",
    "Barney's Version":"nom",
    "The Way Back":"nom",
    "Star Trek":"win",
    "Il Divo":"nom",
    "The Young Victoria":"nom",
    "The Dark Knight":"nom",
    "Hellboy II: The Golden Army":"nom",
    "La Vie en Rose":"win",
    "Norbit":"nom",
    "Pirates of the Caribbean: At World's End":"nom",
    "Pan's Labyrinth":"win",
    "Apocalypto":"nom",
    "Click":"nom",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe":"win",
    "Cinderella Man":"nom",
    "Star Wars Episode III: Revenge of the Sith":"nom",
    "Lemony Snicket's A Series of Unfortunate Events":"win",
    "The Passion of the Christ":"nom",
    "The Sea Inside":"nom",
    "Pirates of the Caribbean: The Curse of the Black Pearl":"nom",
    "Frida":"win",
    "The Time Machine":"nom",
    "Dr. Seuss' How the Grinch Stole Christmas":"win",
    "The Cell":"nom",
    "Shadow of the Vampire":"nom",
    "Topsy-Turvy":"win",
    "Austin Powers: The Spy Who Shagged Me":"nom",
    "Bicentennial Man":"nom",
    "Life":"nom"
};

var VFX = {
    "name":"VFX",
    "Gravity":"nom",
    "Life of Pi":"win",
    "Hugo":"win",
    "Inception":"win",
    "Avatar":"win",
    "District 9":"nom",
    "The Curious Case of Benjamin Button":"win",
"Raiders of the Lost Ark":"win",
"E.T.":"win",
"Forrest Gump":"win",
"Apollo 13":"nom",
"Babe":"win",
"Titanic":"win",
"Gladiator":"win",
"The Lord of the Rings: The Fellowship of the Ring":"win",
"The Lord of the Rings: The Two Towers":"win",
"The Lord of the Rings: The Return of the King":"win",
"Master and Commander: The Far Side of the World":"nom",
    "The Hobbit: An Unexpected Journey":"nom",
    "The Avengers":"nom",
    "Prometheus":"nom",
    "Snow White and the Huntsman":"nom",
    "The Hobbit: The Desolation of Smaug":"nom",
    "Iron Man 3":"nom",
    "The Lone Ranger":"nom",
    "Star Trek: Into Darkness":"nom",
    "Harry Potter and the Deathly Hallows: Part 2":"nom",
    "Real Steel":"nom",
    "Rise of the Planet of the Apes":"nom",
    "Transformers: Dark of the Moon":"nom",
    "Alice in Wonderland":"nom",
    "Harry Potter and the Deathly Hallows: Part 1":"nom",
    "Hereafter":"nom",
    "Iron Man 2":"nom",
    "Star Trek":"nom",
    "The Dark Knight":"nom",
    "Iron Man":"nom",
    "The Golden Compass":"win",
    "Pirates of the Caribbean: At World's End":"nom",
    "Transformers":"nom",
    "Pirates of the Caribbean: Dead Man's Chest":"win",
    "Poseidon":"nom",
    "Superman Returns":"nom",
    "King Kong":"win",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe":"nom",
    "War of the Worlds":"nom",
    "Spider-Man 2":"win",
    "I, Robot":"nom",
    "Harry Potter and the Prisoner of Azkaban":"nom",
    "Pirates of the Caribbean: The Curse of the Black Pearl":"nom",
    "Spider-Man":"nom",
    "Star Wars Episode II: Attack of the Clones":"nom",
    "Artificial Intelligence: AI":"nom",
    "Pearl Harbor":"nom",
    "Hollow Man":"nom",
    "The Perfect Storm":"nom",
    "The Matrix":"win",
    "Star Wars Episode I: The Phantom Menace":"nom",
    "Stuart Little":"nom",
    "What Dreams May Come":"win",
    "Armageddon":"nom",
    "Mighty Joe Young":"nom"
};
